from typing import List

from pydantic import BaseModel, Field


class Planner(BaseModel):
    summary: str = Field(
        description="Full trip summary generated by the planner"
    )
    follow_up_questions: List[str] = Field(
        description="List of follow-up questions to clarify or refine the trip plan"
    )

    def to_dict(self) -> dict:
        return {
            "summary": self.summary,
            "follow_up_questions": self.follow_up_questions,
        }
