TOOLS_NODE = "tools"
INPUT_GUARDRAIL_NODE = "input_guardrail"
INIT_NODE = "init"
CHAT_NODE = "chat"
FOLLOW_UP_QUESTION_NODE = "follow_up_question"
SEARCH_RESULT_MAPPER_NODE = "search_result_mapper"
MERGER_NODE = "merger"
OUTPUT_GUARDRAILS_NODE = "output_guardrail"
